name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - mlflow=1.30.0
  - ipython=7.21.0
  - notebook=6.2.0
  - jupyterlab=3.0.10
  - cookiecutter=1.7.2
  - hydra-core=1.3.1
  - matplotlib=3.3.4
  - pandas=1.2.3
  - git=2.30.2
  - pip=22.2.2
  - pip:
      - wandb==0.13.5
